/* tslint:disable */
/* eslint-disable */
/**
 * Guess The Number API
 * API for Guess The Number game
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RankingTableRow
 */
export interface RankingTableRow {
    /**
     * The name of the player
     * @type {string}
     * @memberof RankingTableRow
     */
    name?: string;
    /**
     * The player's total score
     * @type {number}
     * @memberof RankingTableRow
     */
    score?: number;
}

/**
 * Check if a given object implements the RankingTableRow interface.
 */
export function instanceOfRankingTableRow(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RankingTableRowFromJSON(json: any): RankingTableRow {
    return RankingTableRowFromJSONTyped(json, false);
}

export function RankingTableRowFromJSONTyped(json: any, ignoreDiscriminator: boolean): RankingTableRow {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'score': !exists(json, 'score') ? undefined : json['score'],
    };
}

export function RankingTableRowToJSON(value?: RankingTableRow | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'score': value.score,
    };
}

