/* tslint:disable */
/* eslint-disable */
/**
 * Guess The Number API
 * API for Guess The Number game
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ScoreResponse
 */
export interface ScoreResponse {
    /**
     * The player's total score calculated based on the points and multiplier values submitted
     * @type {number}
     * @memberof ScoreResponse
     */
    roundedNumber?: number;
}

/**
 * Check if a given object implements the ScoreResponse interface.
 */
export function instanceOfScoreResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ScoreResponseFromJSON(json: any): ScoreResponse {
    return ScoreResponseFromJSONTyped(json, false);
}

export function ScoreResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScoreResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'roundedNumber': !exists(json, 'roundedNumber') ? undefined : json['roundedNumber'],
    };
}

export function ScoreResponseToJSON(value?: ScoreResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'roundedNumber': value.roundedNumber,
    };
}

